package ru.siberian.huawei.LogSaver.manageXML.clasess.tg;

public class N7TG_SOFTX3000 extends TG_SOFTX3000{

    private String ABT;
    private String CAMA;
    private String CC;
    private String CCN;
    private String CCRN;
    private String CCT;
    private String CCV;
    private String CNA;
    private String CNSF;
    private String CP;
    private String CPBRM;
    private String CPBTM;
    private String CRF;
    private String CRNA;
    private String CSC;
    private String CSM;
    private String CT;
    private String DI;
    private String DISP;
    private String DOD2;
    private String DV;
    private String EA;
    private String ECCAP;
    private String ECHAIR;
    private String EID;
    private String EVA;
    private String EXTOLP;
    private String G;
    private String GAINV;
    private String GTS;
    private String HCIC;
    private String HOPFL;
    private String HOPVL;
    private String HROM;
    private String HT;
    private String ICPR;
    private String ICR;
    private String IGCF;
    private String INANI;
    private String IPM;
    private String IRCM;
    private String IRCMF;
    private String ISBF;
    private String ISCLR;
    private String ISDP;
    private String ISM;
    private String ISPCLD;
    private String IT;
    private String ITC;
    private String LCIC;
    private String LISTOFCODEC;
    private String LMTGRP;
    private String LT;
    private String MAX;
    private String MAXDM;
    private String MAXDP;
    private String MAXI;
    private String MAXO;
    private String MPTP;
    private String NIC;
    private String NICF;
    private String NIF;
    private String NMSRC;
    private String NOAA;
    private String NPCLD;
    private String OCR;
    private String OLPCLD;
    private String ORCM;
    private String ORCMF;
    private String OTCS;
    private String OUTANI;
    private String PPC;
    private String PRTFLG;
    private String RCHS;
    private String RCN;
    private String RCNM;
    private String RIIND;
    private String RIVAL;
    private String SDPC;
    private String SGCTRL;
    private String SOPC;
    private String SRC;
    private String SRM;
    private String SRO;
    private String SRSM;
    private String STM;
    private String STSM;
    private String SVRCTRL;
    private String SVRCTRLS;
    private String SVRCTRLT;
    private String TC;
    private String TCN;

    private String TGP;
    private String TIMGI;
    private String TM;
    private String UL;
    private String UPF;
    private String VTG;

    private String type = "SS7";

    {
        super.type = this.type;
    }
}
